### ISSUE TITLE
您好，想请问一下这个状况如何解决呢，谢谢！

### ISSUE THREAD

**Issue by jenniferrrWu** [JiChao99/GPT3.5-H5-lite-page#2]
并没有频繁访问，使用的是本地的httpserver和科学上网，访问时携带了key，但是发送信息后控制台报错：jquery.min.js:2 
       POST https://api.openai.com/v1/chat/completions 429 (Too Many Requests)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
fetchMessages @ index.html?
（匿名） @ index.html?key
y.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
（匿名） @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
E.fn.<computed> @ jquery.min.js:2
（匿名） @ index.html?key=
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
jquery.min.js:2 XHR 加载失败：POST“https://api.openai.com/v1/chat/completions”。
界面报错：
Oops, something went wrong with the server. Please try again later.

**Comment by JiChao99** [comment]
确认你自己的网络没问题的话，429就是超限了（可能和最近 `OPEN AI` 使用量比较大有关，有改限制）

另外不要把自己的 `key` 放出来，避免泄露

**Comment by jenniferrrWu** [comment]
> 确认你自己的网络没问题的话，429就是超限了（可能和最近 使用量比较大有关，有改限制）`OPEN AI`
> 
> 另外不要把自己的 放出来，避免泄露`key`

谢谢我知道了，我再看看！

**Comment by jenniferrrWu** [comment]
> 确认你自己的网络没问题的话，429就是超限了（可能和最近 使用量比较大有关，有改限制）`OPEN AI`
> 
> 另外不要把自己的 放出来，避免泄露`key`

有点绝望，换了个openai账号的key还是不太行，最近官方的限制吗TT。。

**Comment by JiChao99** [comment]
看了下最近是不太稳定 https://status.openai.com/

这个项目是个简单的直调，应该不会有其他问题

同时这个项目也不适合复杂场景使用（上下文只是完整拼接，没有特殊优化），有其他需求也可以看下其他项目 or PR

**Comment by jenniferrrWu** [comment]
感谢老兄，我这想用本地的httpserver登录（项目需要），已经把我的key写入代码中了，但是反复尝试还是无法成功发送，我是个菜鸟，网上资料也较少，头疼一天了，还挺棘手的哈哈。。POST https://api.openai.com/v1/chat/completions 429 (Too Many Requests)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
fetchMessages @ index.html?key=。。。。
（匿名） @ index.html?key=。。。。
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
jquery.min.js:2 XHR 加载失败：POST“https://api.openai.com/v1/chat/completions”。
